### ISSUE TITLE
Initializer for conditional binding must have Optional type, not '() -> Void' in SprenUi GreetingScreen

### ISSUE THREAD

**Issue by rogerheykoop** [Elite-HRV/spren-vision-ios#34]
During compilation of our (Swift 5) IOS app I suddenly get this error. 

The error occurs in line 21 of GreetingScreen during a build. 

![image](https://user-images.githubusercontent.com/665824/229808893-06cbec44-5622-4702-a0b0-b4f4e4708edb.png)

This is when using the main version of spren-vision-ios.

**Comment by DasserBasyouni** [comment]
This bug is happening with me as well right after updating to Xcode `14.3`.
